FROM ghcr.io/astral-sh/uv:python3.12-bookworm as uv-source
FROM nvcr.io/nvidia/cuda:12.9.1-base-ubuntu20.04

COPY --from=uv-source / /

WORKDIR /home

RUN git clone https://github.com/facebookresearch/sam2.git
RUN mkdir -p /app

RUN git clone git@github.com:kazewong/SAM2RAG.git

WORKDIR /home/SAM2RAG

RUN uv sync
RUN uv pip install -e /home/sam2/
