FROM ghcr.io/astral-sh/uv:python3.12-bookworm as uv-source
FROM pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime

COPY --from=uv-source / /

WORKDIR /home

RUN git clone https://github.com/facebookresearch/sam2.git
RUN git clone git@github.com:kazewong/SAM2RAG.git

WORKDIR /home/SAM2RAG

RUN uv sync
RUN uv pip install -e /home/sam2/
